/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistem_ATM;

import javax.swing.JOptionPane;

/**
 *
 * @author alyag
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class menu_ATM extends javax.swing.JFrame {

    /**
     * Creates new form menu_ATM
     */
    public menu_ATM() {
        initComponents();
        setLocationRelativeTo(null);
        
        String akunLogin = login.MainApp.akunLogin;

        if (akunLogin == null || akunLogin.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Akun login tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Query untuk mengambil nama lengkap berdasarkan nomor rekening
        String sql = "SELECT nama_lengkap FROM user WHERE nomor_rekening = ?";
        Connection con1 = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            // Membuat koneksi ke database
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_bank", "root", "");

            // Menyiapkan PreparedStatement untuk query
            pstmt = con1.prepareStatement(sql);
            pstmt.setString(1, akunLogin); // Set nomor rekening sebagai parameter query

            // Eksekusi query
            rs = pstmt.executeQuery();

            if (rs.next()) {
                String nama = rs.getString("nama_lengkap"); // Ambil nama lengkap dari hasil query
                jLabel9.setText(akunLogin + " (" + nama + ")");
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan untuk akun ini!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: Driver tidak ditemukan.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Menutup koneksi dan resource setelah digunakan
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pstmt != null) {
                    pstmt.close();
                }
                if (con1 != null) {
                    con1.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonCekSaldo = new javax.swing.JButton();
        jButtonCekMutasi = new javax.swing.JButton();
        jButtonCekPIN = new javax.swing.JButton();
        jButtonTransfer = new javax.swing.JButton();
        jButtonSetorTunai = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonTarikTunai = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transaksi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Silakan pilih transaksi yang ingin Anda lakukan");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("-");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addContainerGap(350, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jButtonCekSaldo.setBackground(new java.awt.Color(0, 51, 102));
        jButtonCekSaldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonCekSaldo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCekSaldo.setText("Cek Saldo");
        jButtonCekSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCekSaldoActionPerformed(evt);
            }
        });

        jButtonCekMutasi.setBackground(new java.awt.Color(0, 51, 102));
        jButtonCekMutasi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonCekMutasi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCekMutasi.setText("Cek Mutasi");
        jButtonCekMutasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCekMutasiActionPerformed(evt);
            }
        });

        jButtonCekPIN.setBackground(new java.awt.Color(0, 51, 102));
        jButtonCekPIN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonCekPIN.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCekPIN.setText("Cek PIN");
        jButtonCekPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCekPINActionPerformed(evt);
            }
        });

        jButtonTransfer.setBackground(new java.awt.Color(0, 51, 102));
        jButtonTransfer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonTransfer.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTransfer.setText("Transfer");
        jButtonTransfer.setToolTipText("");
        jButtonTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferActionPerformed(evt);
            }
        });

        jButtonSetorTunai.setBackground(new java.awt.Color(0, 51, 102));
        jButtonSetorTunai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonSetorTunai.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSetorTunai.setText("Setor Tunai");
        jButtonSetorTunai.setToolTipText("");
        jButtonSetorTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetorTunaiActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/saldo.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/financial-history.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/padlock (1).png"))); // NOI18N

        jButtonTarikTunai.setBackground(new java.awt.Color(0, 51, 102));
        jButtonTarikTunai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonTarikTunai.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTarikTunai.setText("Tarik Tunai");
        jButtonTarikTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTarikTunaiActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transaction.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wallet.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/money-withdraw.png"))); // NOI18N

        jButtonBack.setBackground(new java.awt.Color(0, 51, 102));
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow.png"))); // NOI18N
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCekMutasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCekSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCekPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonTarikTunai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSetorTunai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonCekMutasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(jButtonTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonCekSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addComponent(jButtonSetorTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(1, 1, 1))))
                    .addComponent(jLabel3))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCekPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonTarikTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCekMutasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCekMutasiActionPerformed
        // TODO add your handling code here:
        Sistem_ATM.tableCekMutasi mutasi = new Sistem_ATM.tableCekMutasi();
        mutasi.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCekMutasiActionPerformed

    private void jButtonTarikTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTarikTunaiActionPerformed
        // TODO add your handling code here:
        Sistem_ATM.tarikTunai frame = new Sistem_ATM.tarikTunai();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonTarikTunaiActionPerformed

    private void loadSaldo() {
        String akunLogin = login.MainApp.akunLogin; // Ambil informasi akun login dari MainApp

        if (akunLogin == null || akunLogin.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Akun login tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sql = "SELECT nama_lengkap, saldo FROM user WHERE nomor_rekening = ?"; // Query berdasarkan akun login
        Connection con1 = null;  // Koneksi ke database
        PreparedStatement pstmt = null;  // PreparedStatement untuk query
        ResultSet rs = null;  // Menampung hasil query

        try {
            // Membuat koneksi ke database menggunakan DriverManager
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_bank", "root", "");

            // Siapkan PreparedStatement
            pstmt = con1.prepareStatement(sql);
            pstmt.setString(1, akunLogin); // Gunakan akun login sebagai parameter

            // Eksekusi query
            rs = pstmt.executeQuery();

            if (rs.next()) {
                String nama = rs.getString("nama_lengkap");
                double saldo = rs.getDouble("saldo");

                // Simpan saldo di variabel global
                login.MainApp.saldo = saldo;

                // Akses frame cekSaldo
                cekSaldo cekSaldoFrame = new cekSaldo(); // Buat objek frame cekSaldo
                cekSaldoFrame.setVisible(true); // Tampilkan frame
                dispose(); // Tutup frame saat ini
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan untuk akun ini!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: Driver tidak ditemukan.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Pastikan koneksi dan resource lainnya ditutup setelah digunakan
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pstmt != null) {
                    pstmt.close();
                }
                if (con1 != null) {
                    con1.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }


    private void jButtonCekSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCekSaldoActionPerformed
        // TODO add your handling code here:
        loadSaldo();
    }//GEN-LAST:event_jButtonCekSaldoActionPerformed

    private void loadPin() {
        String akunLogin = login.MainApp.akunLogin; // Ambil informasi akun login dari MainApp

        if (akunLogin == null || akunLogin.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Akun login tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sql = "SELECT pin FROM user WHERE nomor_rekening = ?"; // Query untuk mengambil PIN berdasarkan akun login
        Connection con1 = null;  // Koneksi ke database
        PreparedStatement pstmt = null;  // PreparedStatement untuk query
        ResultSet rs = null;  // Menampung hasil query

        try {
            // Membuat koneksi ke database menggunakan DriverManager
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_bank", "root", "");

            // Siapkan PreparedStatement
            pstmt = con1.prepareStatement(sql);
            pstmt.setString(1, akunLogin); // Gunakan akun login sebagai parameter

            // Eksekusi query
            rs = pstmt.executeQuery();

            if (rs.next()) {
                String pin = rs.getString("pin");  // Ambil PIN dari database

                if (pin != null && !pin.isEmpty()) {
                    // Simpan PIN di variabel global
                    login.MainApp.pin = pin;

                    cekPIN cekPINFrame = new cekPIN();
                    cekPINFrame.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "PIN tidak ditemukan atau kosong untuk akun ini!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan untuk akun ini!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: Driver tidak ditemukan.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Pastikan koneksi dan resource lainnya ditutup setelah digunakan
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pstmt != null) {
                    pstmt.close();
                }
                if (con1 != null) {
                    con1.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    private void jButtonCekPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCekPINActionPerformed
        // TODO add your handling code here
        loadPin();
    }//GEN-LAST:event_jButtonCekPINActionPerformed

    private void jButtonTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferActionPerformed
        // TODO add your handling code here:
        Sistem_ATM.transfer frame = new Sistem_ATM.transfer();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonTransferActionPerformed

    private void jButtonSetorTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetorTunaiActionPerformed
        // TODO add your handling code here:
        Sistem_ATM.setorTunai frame = new Sistem_ATM.setorTunai();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonSetorTunaiActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        AwalHalamanUtama.HalamanUtama frame = new AwalHalamanUtama.HalamanUtama();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_ATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCekMutasi;
    private javax.swing.JButton jButtonCekPIN;
    private javax.swing.JButton jButtonCekSaldo;
    private javax.swing.JButton jButtonSetorTunai;
    private javax.swing.JButton jButtonTarikTunai;
    private javax.swing.JButton jButtonTransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
